package ui;

import util.Session;

/**
 *
 * @author PMateus <paulomatew@gmailcom>
 */
public class ComoJogar extends javax.swing.JPanel {

    /**
     * Creates new form ComoJogar
     */
    public ComoJogar() {
        initComponents();

        Session.JFramePrincipal.changeTitleText("Sobre");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 80, 40));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Stop! é um jogo muito popular no Brasil, conhecido também como \"Adedanha\", \"Adedonha\", \"Salada de Frutas\", \"Uestope\" ou \"Nome-Lugar-Objeto\".\n\nA princípio devem ser escolhidos temas, que posteriormente servirão como base para a dinâmica do jogo. Exemplos de temas são: \"Nome\", \"Cor\", \"Animal\", dentre outros. Uma vez com os temas definidos, será sorteada uma letra e inicia-se uma rodada. Todos devem responder cada tema com a letra sorteada. Ao responder sobre os temas, encerre a rodada, mas atenção: quanto mais rápido você terminar de responder, maior é sua bonificação.\n\nA validade de cada resposta para cada tema é conferida pelos próprios participantes. Marque com SIM ou NÃO assim que todos terminarem de responder. Para cada SIM, atribui-se 17 pontos ao Jogador que deu esta resposta. Para cada NÃO, atribui-se 0 pontos. A bonificação por velocidade é dada pela QUANTIDADE_DE_PARTICIPANTES * 7, para o primeiro a encerrar o round, (QUANTIDADE_DE_PARTICIPANTES - 1) * 7 para o 2º a encerrar o round, e assim sucessivamente.\n\nO processo é repetido até atingir um número de rodadas específico.\n\nOBS.:\nPara CRIAR uma sala, vá em \"novo jogo\", configure a partida e crie. Espere os outros participantes entrarem na sala e inicie o jogo.\n\nPara ENTRAR em uma sala, vá em \"entrar em um jogo\", selecione um NOVO nickname, insira o ip da sala em questão e entre.\n\n\nATALHOS:\nAo selecionar o campo de inserir as respostas para os temas:\nTAB-> Avança para o próximo tema.\nSHIFT-> Volta para o tema anterior.\nENTER-> Encerra o seu round.\n\nBOM JOGO!");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 79, 380, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telajogar.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 620, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Session.JFramePrincipal.changeScreen(new MainMenu());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
