package ui;

import java.util.Timer;
import java.util.TimerTask;
import entidades.network.DataNetworkManager;
import util.Session;

/**
 *
 * @author PMateus <paulomatew@gmailcom>
 */
public class GameScreenWaitingRoomPosValidation extends javax.swing.JPanel {

    public String txt = "Aguardando os outros jogadores...";
    private Timer handler = new Timer(), handlerChecker = new Timer();

    public void threadChecker() {
        TimerTask tarefa = new TimerTask() {
            @Override
            public void run() {
                if (Session.isServidor) {
                    int falta = Session.conexaoServidor.networkClientsSockets.size() - DataNetworkManager.respostasRecebidasValidated.size();
                    jLabelPlayersRemaing.setText(String.valueOf(falta));
                    if (DataNetworkManager.respostasRecebidasValidated.size()
                            == Session.conexaoServidor.networkClientsSockets.size()) {
                        calcularPontuacao();
                        cancelAllThreads();
                    }
                } else {
                    if (Session.canValidateRespostas) {
                        Session.canValidateRespostas = false;
                        Session.JFramePrincipal.changeScreen(new GameScreenValidation());
                        cancelAllThreads();
                    } else if (Session.canShowHighScores) {
                        Session.canShowHighScores = false;
                        Session.JFramePrincipal.changeScreen(new HighScore());
                        cancelAllThreads();
                    } else if (Session.canStartGame) {
                        Session.canStartGame = false;
                        Session.JFramePrincipal.changeScreen(new GameScreen());
                        cancelAllThreads();
                    }
                }
            }

        };
        handlerChecker.scheduleAtFixedRate(tarefa, 0, 100);
    }

    private void cancelAllThreads() {
        try {
            if (handlerChecker != null) {
                handlerChecker.cancel();
            }
        } catch (Exception e) {
            e.getStackTrace();
        }
    }

    private void calcularPontuacao() {
        Session.gRunTime.addScore(DataNetworkManager.sv_sumScore());
        String[] ips = Session.conexaoServidor.getIpsNetwork();
        for (int i = 0; i < ips.length; i++) {
            //Não deixo enviar para o mesmo ip da máquina servidor.
            if (ips[i].equals(Session.masterIP)) {
                continue;
            }
            Session.conexaoCliente.sv_communicateScores(ips[i], Session.gRunTime.pontuacaoDoRound);
        }
        Session.JFramePrincipal.changeScreen(new HighScore());
    }

    public GameScreenWaitingRoomPosValidation() {
        initComponents();
        Session.JFramePrincipal.changeTitleText("Aguardando Jogadores");
        threadChecker();

        if (Session.isServidor) {
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabelPlayersRemaing.setVisible(true);
            jButton2.setVisible(true);
        } else {
            Session.conexaoServidor.ListeningShowScore();
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabelPlayersRemaing.setVisible(false);
            jButton2.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelPlayersRemaing = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText(txt);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jButton1.setText("Sair do JOGO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, 380, 10));

        jButton2.setText("Forçar inicio do ROUND");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 273, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("(apenas para o Criador da sala)");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 275, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Jogadores restantes:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jLabelPlayersRemaing.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPlayersRemaing.setForeground(new java.awt.Color(0, 0, 204));
        jLabelPlayersRemaing.setText("jLabel4");
        add(jLabelPlayersRemaing, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 105, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        calcularPontuacao();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Session.clearAllData();

        Session.JFramePrincipal.changeScreen(new MainMenu());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelPlayersRemaing;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
